spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-server.c5skqmuocss0.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=fullstack
    username: postgres
    password: 1q2w3e4r

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
